version: '3.9'

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: mhrs_jenkins
    ports:
      - "8080:8080"    # Jenkins web arayüzü
      - "50000:50000"  # Jenkins agent portu
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mhrs_db
    environment:
      MYSQL_ROOT_PASSWORD: mysecurepassword
      MYSQL_DATABASE: mhrsdb
      MYSQL_USER: mhrsuser
      MYSQL_PASSWORD: mhrspass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  mhrs_app:
    build: . 
    container_name: mhrs_web
    ports:
      - "5000:80"      # Dışarıdan 5000'e geleni Nginx'in 80 portuna yönlendirir
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  jenkins_home:
  mariadb_data: