services:
db:
    image: mariadb:latest
    container_name: mhrs_db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=12345
      - MARIADB_DATABASE=mhrs
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mhrs-projesi/init.sql:/docker-entrypoint-initdb.d/init.sql 
web:
    build: .
    container_name: mhrs_web
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data: